ugahacks/ugahacks-backend

- projects/mybyte/components/loginError.tsx
- projects/mybyte/pages/login.tsx
Completed Issue #5 
The error shows itself on the page instead of an alert.
> Added login error to the page instead of as an alert

- projects/mybyte/components/RegisterCard.tsx
- projects/mybyte/components/colorCode.tsx
- projects/mybyte/pages/events/hacks-8.tsx
Color coded status of registration as detailed in issue #9 . Also made the disabled cards be as transparent as their enabled counterparts (seemed confusing for it not to).
> Feature/create component is color coded#9

- projects/mybyte/context/AuthContext.tsx
Use prod settings for collections name
> Enable prod settings

- projects/mybyte/context/AuthContext.tsx
> Small chagnge

- projects/mybyte/context/AuthContext.tsx
Reverts ugahacks/ugahacks-backend#57
> Revert "Small chagnge"

- projects/mybyte/components/navbar.tsx
Reverts ugahacks/ugahacks-backend#55
> Revert "Changed"

- projects/mybyte/pages/login.tsx
Reverts ugahacks/ugahacks-backend#54
> Revert "Change"

- .gitignore
Reverts ugahacks/ugahacks-backend#53
> Revert "emergency"

- projects/mybyte/pages/qrRead.tsx
> Commit fixes

- projects/mybyte/context/AuthContext.tsx
- projects/mybyte/pages/team.tsx
Team email validation is client-side now.
> Fixed teams

- projects/mybyte/context/AuthContext.tsx
- projects/mybyte/pages/team.tsx
Made the method to give points to entire team. compliant with firestore rules.
> Give Team Points

- projects/mybyte/components/ProtectedRoute.tsx
- projects/mybyte/components/loginError.tsx
- projects/mybyte/components/navbar.tsx
- projects/mybyte/context/AuthContext.tsx
- projects/mybyte/pages/_app.tsx
- projects/mybyte/pages/_document.tsx
- projects/mybyte/pages/dashboard.tsx
- projects/mybyte/pages/index.tsx
- projects/mybyte/pages/login.tsx
- projects/mybyte/pages/signup.tsx
- projects/mybyte/styles/globals.css
- projects/mybyte/tailwind.config.js
Fixed the scrolling issue. Body now does not scroll, but the main content does have a scrollbar when it needs it.
- Main page is scrollable now
No
No
No
> Fixed the scrolling issue hopefully

- projects/mybyte/Dockerfile
> Updated dockerfile, deployment failure fix

- projects/mybyte/Dockerfile
- projects/mybyte/pages/dashboard.tsx
> Trigger CI/CD, build bugfix

- package.json
- yarn.lock
> Added react to project dependencies for react-particles

- projects/mybyte/components/navbar.tsx
> Trigger deployment

- projects/mybyte/package.json
- yarn.lock
> Last try, added tsparticles dependencies to package.json

- projects/mybyte/components/Confetti.tsx
- projects/mybyte/pages/dashboard.tsx
- projects/mybyte/pages/registrationSuccess.tsx
> Fixed mobile bug with tile not being clickable

- projects/mybyte/package.json
- yarn.lock
Added react-typewriter to package.json
> Added react-typewriter to package.json

- projects/mybyte/package.json
- yarn.lock
This will work 😒
updated package.json
> Typewriter effect added to package.json

- projects/mybyte/enums/registerEnums.ts
- projects/mybyte/pages/register.tsx
Included more information on EL Credit, included Dr. Cotterell's suggestion.
/register.tsx EL Credit got turned into a drop down.
No.
No.
No.
> Added Cotterell's changes to EL Credit interest form

- projects/mybyte/context/AuthContext.tsx
Included checked-in to user schema
> Added checked in

- projects/mybyte/context/AuthContext.tsx
- projects/mybyte/pages/register.tsx
Added checkout fields to firebase.
> Added checkout fields

- projects/mybyte/pages/resetPassword.tsx
Added mobile view for resetPassword page
> Added mobile view

- projects/mybyte/context/AuthContext.tsx
Reset's user's point to 0 upon registration.
AuthContext.tsx
No.
No.
No, not needed.
> Reset user's points to 0 on registration

- README.md
- projects/ugahacks-mobile/package.json
- yarn.lock
updated readme.md + removed ugahacks-mobile from monorepo
> Removed ugahacks-mobile repo + updated readme

- projects/mybyte/components/navbar.tsx
> disabled team hotfix

- projects/mybyte/components/Confetti.tsx
> build issue

- projects/mybyte/package.json
- yarn.lock
> updating react

- projects/mybyte/package.json
- yarn.lock
> downgraded to react 18.2.19

- projects/mybyte/package.json
- yarn.lock
Updated Material Tailwind to V2.1.6
Downgraded to @types/react@18.2.18
> Fixed material tailwind typescript bug

- projects/mybyte/components/Confetti.tsx
> Included tsparticles engine type to Confetti animation

- package.json
- yarn.lock
> updated tsparticles

- projects/mybyte/components/Confetti.tsx
> trigger ci/cd

- package.json
- projects/mybyte/components/Confetti.tsx
- projects/mybyte/package.json
- yarn.lock
> changed callback to type any

- package.json
- projects/mybyte/components/Confetti.tsx
- yarn.lock
> Updated tsparticles, used tsparticles boilerplate

- projects/mybyte/tsconfig.json
> added @types to tsconfig

- projects/mybyte/package.json
- yarn.lock
> added types

- package.json
- projects/mybyte/package.json
- yarn.lock
> Reverted package.json to master

- projects/mybyte/tsconfig.json
> this will work :)

- projects/mybyte/pages/register.tsx
Increased padding for mobile registration form
> fixed mobile form for Gargee and Julie

- projects/mybyte/components/MobileDashboard.tsx
Increased padding on dashboard mobile view
> Increased padding on dashboard mobile view

- projects/mybyte/pages/index.tsx
increased padding on mobile dashboard view
> mobile dash fixed

- README.md
updated readme to include ci/cd badges
> updated readme to include ci/cd badges

- projects/mybyte/components/EventRect.tsx
- projects/mybyte/pages/dashboard.tsx
> manually disabled hacks9 registration now that deadline has passed

- projects/mybyte/components/EventRect.tsx
- projects/mybyte/pages/dashboard.tsx
Manually disable hacks9 registration now that deadline has passed to hotfix changing system time to get around the registration deadline.
- manually disable hacks9 registration
no
no
> Manually Disable Hacks 9 Registration

- projects/mybyte/context/AuthContext.tsx
- projects/mybyte/pages/qrRead.tsx
Added functionalities to the scanner according to https://discord.com/channels/1097912794701103204/1203389859671314502/1204494446792671272
- subtract points only if user has enough points
- checkin/checkout functionality
- basic feedback on outcome of the scan
:(
no
ye
> Scanner Features

- projects/mybyte/context/AuthContext.tsx
- projects/mybyte/pages/qrRead.tsx
- scanner shows t shirt size and name of the person being scanned
- user must now be registered for hacks9 to be checked in
no
no 
ye
> Scanner gives T shirt and name when scanning

- projects/mybyte/pages/qrRead.tsx
> scanner looping fix perhaps

- projects/mybyte/pages/qrRead.tsx
> scanner try again

- projects/mybyte/context/AuthContext.tsx
- projects/mybyte/package.json
- projects/mybyte/pages/qrRead.tsx
- yarn.lock
> Hopefully fixing scanner

- projects/mybyte/pages/qrRead.tsx
> tryna fix scanna

- projects/mybyte/pages/qrRead.tsx
> scanner? ion even know her

- projects/mybyte/pages/qrRead.tsx
> scanner STYLING

- projects/mybyte/context/AuthContext.tsx
> Fix compile errors

- projects/mybyte/pages/register.tsx
- yarn.lock
> add red asterisk

- .github/workflows/cicd_master.yaml
- projects/mybyte/pages/esports.tsx
> updated CICD, hopefully it will work!
